#!/usr/bin/env python3
"""Generate the Maison's folder-based, progressively enhanced static storefront."""
from pathlib import Path
import json, html, shutil, os

ROOT = Path(__file__).resolve().parents[1]
SITE = json.loads((ROOT/'data/site.json').read_text())
PRODUCTS = json.loads((ROOT/'data/catalog.json').read_text())
BASE = '' # URLs are relative to the document <base> element.
ORIGIN = os.environ.get('SITE_ORIGIN', SITE['origin']).rstrip('/')
EMAIL = SITE['email']
BRAND = SITE['name']
PREVIEW = os.environ.get('SITE_PREVIEW',str(SITE.get('preview',True))).lower() == 'true'
ROUTES = []
NAV = [('gifts','Gifts'),('handbags','Handbags'),('women','Women'),('men','Men'),('new-in','New in'),('children','Children'),('travel','Travel'),('jewellery-watches','Jewellery & Watches'),('decor-lifestyle','Décor & Lifestyle'),('services','LA INFINITÉ Services')]
LEGAL = [('shipping','Shipping & delivery'),('returns','Returns & refunds'),('terms','Terms & conditions'),('privacy','Privacy notice'),('cookies','Cookie policy'),('accessibility','Accessibility')]

def esc(s): return html.escape(str(s),quote=True)
def url(path=''): return path.lstrip('/') or './'
def absolute(path=''): return ORIGIN+'/'+path.lstrip('/')
def link(path,label,cls='',**attrs):
    att=' '.join(f'{k.replace("_","-")}="{esc(v)}"' for k,v in attrs.items())
    return f'<a href="{url(path)}" class="{cls}" {att}>{label}</a>'
def icon(name):
    paths={'menu':'<path d="M3 7h18M3 12h18M3 17h18"/>','search':'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>','user':'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>','bag':'<path d="M5 8h14l1 13H4L5 8Z"/><path d="M8 9V6a4 4 0 0 1 8 0v3"/>','close':'<path d="m5 5 14 14M19 5 5 19"/>','delivery':'<path d="M2 5h12v12H2zM14 10h4l4 4v3h-8"/><circle cx="6" cy="18" r="2"/><circle cx="18" cy="18" r="2"/>'}
    return f'<svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>'
def image(filename,alt,loading='lazy',**attrs):
    att=' '.join(f'{k.replace("_","-")}="{esc(v)}"' for k,v in attrs.items())
    return f'<img src="{url("assets/"+filename)}" alt="{esc(alt)}" loading="{loading}" decoding="async" {att}>'
def money(n): return f'${n:,.2f}'
def heading(title,sub='',eyebrow='The Maison'):
    return f'<section class="page-heading"><p class="eyebrow">{eyebrow}</p><h1>{title}</h1>{f"<p>{sub}</p>" if sub else ""}</section>'
def button(path,text,secondary=False): return link(path,text,'button secondary' if secondary else 'button')
def breadcrumbs(items):
    allitems=[('','Home')]+items
    return '<nav class="breadcrumb" aria-label="Breadcrumb">'+'<span aria-hidden="true">/</span>'.join(link(p,esc(n)) if i<len(allitems)-1 else f'<span aria-current="page">{esc(n)}</span>' for i,(p,n) in enumerate(allitems))+'</nav>'
def header(route):
    nav=''.join(link(s+'/',n,aria_current='page' if route==s+'/' else 'false') for s,n in NAV if s in ['new-in','women','handbags','gifts'])
    return f'''<a class="skip" href="#main">Skip to content</a>
    
    <div class="promo-strip" aria-label="Featured collections">
      <a class="promo-link" href="{url('women/')}">NEW IN / WOMEN</a>
      <a class="promo-link" href="{url('new-in/')}" hidden>DISCOVER / NEW IN</a>
      <a class="promo-link" href="{url('gifts/')}" hidden>GIFTS FOR THE SEASON</a>
    </div>
    <header class="masthead"><div class="header-main"><div class="header-left"><button class="icon-button" data-open="menu-dialog" aria-label="Open menu">{icon('menu')}<span class="header-label">Menu</span></button>{link('contact/','Contact','header-contact fine')}</div>
    <a class="brand" href="{url('')}" aria-label="LA INFINITÉ home">LA INFINITÉ</a>
    <div class="header-right"><button class="icon-button" data-open="search-dialog" aria-label="Search the Maison">{icon('search')}</button>{link('account/',icon('user'),'icon-button account-icon',aria_label='My account')}{link('cart/',icon('bag')+'<span class="cart-counter" data-cart-count>0</span>','icon-button',aria_label='Shopping bag')}</div></div>
    <nav class="desktop-nav" aria-label="Featured collections">{nav}{link("about/","The Maison")}</nav></header>'''
def newsletter():
    return f'''<section class="newsletter" aria-labelledby="newsletter-title"><p class="eyebrow">Letters from the Maison</p><h2 id="newsletter-title">Collection updates.</h2><p>New creations, private collection previews, and news from LA INFINITÉ.</p><form class="newsletter-form" data-newsletter><label class="fine" for="newsletter-email">Email address</label><div class="email-field"><input type="email" id="newsletter-email" name="email" autocomplete="email" placeholder="Your email address" required maxlength="254"><button type="submit">Subscribe</button></div><label class="consent"><input type="checkbox" name="consent" required><span>I would like to receive email updates from LA INFINITÉ. I can unsubscribe at any time. {link('privacy/','Privacy notice')}.</span></label><p class="status-message" role="status" data-form-status></p></form></section>'''
def footer():
    return f'''<footer class="footer"><div class="footer-grid"><div><h3>LA INFINITÉ</h3><p>Founded in 2019.<br>Italian craftsmanship.<br>A personal expression of the exceptional.</p>{link('about/','Discover the Maison')}</div><div><h3>Client services</h3>{link('contact/','Contact us')}{link('shipping/','Shipping & delivery')}{link('returns/','Returns & refunds')}{link('size-guide/','Size guide')}{link('care/','Care for your creation')}</div><div><h3>Your Maison</h3>{link('account/','My account')}{link('cart/','Shopping bag')}{link('rewards/','Maison Circle')}{link('services/','LA INFINITÉ Services')}{link('new-in/','New in')}</div><div><h3>Information</h3>{link('terms/','Terms & conditions')}{link('privacy/','Privacy notice')}{link('cookies/','Cookie policy')}<button class="link-button" data-cookie-settings>Cookie preferences</button>{link('accessibility/','Accessibility')}{link('sitemap/','Sitemap')}</div></div><div class="footer-wordmark" aria-hidden="true">LA INFINITÉ<sup>™</sup></div><div class="footer-bottom"><p>© 2026 LA INFINITÉ (Pty) Ltd. All rights reserved.</p><span>International · English · USD $</span></div></footer>'''
def dialogs():
    nav=''.join(link(s+'/',esc(n)) for s,n in NAV)
    return f'''<dialog class="drawer" id="menu-dialog" aria-labelledby="menu-title"><div class="drawer-head"><p id="menu-title">Explore the Maison</p><button class="icon-button" data-close aria-label="Close menu">{icon('close')}</button></div><div class="drawer-body"><nav class="drawer-nav" aria-label="All collections">{nav}</nav><div class="drawer-links">{link('about/','The Maison')}{link('rewards/','Maison Circle')}{link('account/','My account')}{link('contact/','Contact client services')}</div></div></dialog>
    <dialog class="modal" id="search-dialog" aria-labelledby="search-title"><div class="modal-head"><h2 id="search-title">Search the collection</h2><button class="icon-button" data-close aria-label="Close search">{icon('close')}</button></div><form action="{url('search/')}" method="get"><label for="global-search" class="fine">Search the Maison</label><div class="search-box"><input id="global-search" type="search" name="q" placeholder="A creation, a collection, a detail…" autocomplete="off" maxlength="100"><button type="submit" aria-label="Search">{icon('search')}</button></div></form><p class="eyebrow">Discover</p><div class="search-suggestions">{link('products/zebra-stiletto/','The Zebra Stiletto')}{link('products/sac-livoire/','Sac L’Ivoire')}{link('rewards/','Maison Circle')}{link('services/','Client services')}</div></dialog>
    <dialog class="modal large" id="image-dialog" aria-labelledby="image-title"><div class="modal-head"><h2 id="image-title">A closer look</h2><button class="icon-button" data-close aria-label="Close image">{icon('close')}</button></div><img id="zoomed-image" alt=""></dialog>
    <aside id="cookie-banner" class="cookie-banner" aria-label="Cookie choices" hidden><h2>Your privacy, your choice.</h2><p>Essential storage keeps your bag and privacy choices on this device. Optional analytics help us understand browsing activity. You can accept, decline, or change your preferences at any time. {link('cookies/','Read our cookie policy','text-link')}</p><div class="actions"><button class="button secondary" data-cookie-reject>Essential only</button><button class="button" data-cookie-accept>Accept optional</button><button class="text-link cookie-manage" data-cookie-settings>Manage preferences</button></div></aside>
    <dialog class="modal" id="cookie-dialog" aria-labelledby="cookie-title"><div class="modal-head"><h2 id="cookie-title">Cookie preferences</h2><button class="icon-button" data-close aria-label="Close cookie preferences">{icon('close')}</button></div><p class="fine">Your preferences apply to this browser. Declining optional storage does not prevent shopping or contacting the Maison.</p><div class="cookie-option"><div><strong>Essential</strong><p>Your shopping bag, selected country and cookie choices.</p></div><span class="fine">Always on</span></div><label class="cookie-option"><span><strong>Analytics</strong><p>Consent-based browsing measurement. In this first edition, records remain on this device and are not sent to a third party.</p></span><input type="checkbox" id="analytics-consent"></label><p class="fine" style="margin:20px 0">No advertising cookies or third-party analytics are currently used.</p><button class="button full" data-cookie-save>Save preferences</button></dialog>
    <dialog class="modal" id="newsletter-dialog" aria-labelledby="letter-title"><div class="modal-head"><h2 id="letter-title">Join the Maison’s mailing list</h2><button class="icon-button" data-close aria-label="Close subscription request">{icon('close')}</button></div><p>For now, our Client Services team manages subscription requests personally.</p><p class="fine">Continue to open an email addressed to the Maison. Your subscription is not complete until you send that email and our team processes your request.</p><a class="button full" id="newsletter-mail" href="mailto:{EMAIL}">Email my subscription request</a><p class="fine" style="margin-top:18px">You can also write directly to <a href="mailto:{EMAIL}">{EMAIL}</a>.</p></dialog>
    <div id="toast" class="toast" role="status" hidden></div>'''
def graph(route,title,desc,crumbs,products=None,product=None):
    org={'@type':['OnlineStore','Organization'],'@id':absolute()+'#organization','name':BRAND,'legalName':SITE['company'],'url':absolute(),'email':EMAIL,'foundingDate':'2019','brand':{'@id':absolute()+'#brand'},'contactPoint':{'@type':'ContactPoint','email':EMAIL,'contactType':'customer service','availableLanguage':'English'}}
    brand={'@type':'Brand','@id':absolute()+'#brand','name':BRAND}
    website={'@type':'WebSite','@id':absolute()+'#website','url':absolute(),'name':BRAND,'publisher':{'@id':absolute()+'#organization'},'inLanguage':'en'}
    web={'@type':'WebPage','@id':absolute(route)+'#webpage','url':absolute(route),'name':title,'description':desc,'isPartOf':{'@id':absolute()+'#website'},'inLanguage':'en','publisher':{'@id':absolute()+'#organization'}}
    data=[org,brand,website,web]
    if crumbs:
        bread={'@type':'BreadcrumbList','@id':absolute(route)+'#breadcrumb','itemListElement':[{'@type':'ListItem','position':i+1,'name':n,'item':absolute(p)} for i,(p,n) in enumerate([('','Home')]+crumbs)]}
        data.append(bread);web['breadcrumb']={'@id':bread['@id']}
    if products is not None:
        data.append({'@type':'ItemList','name':title,'numberOfItems':len(products),'itemListElement':[{'@type':'ListItem','position':i+1,'url':absolute('products/'+p['id']+'/'),'name':p['fullName']} for i,p in enumerate(products)]})
        web['@type']='CollectionPage'
    if product:
        p=product
        offer={'@type':'Offer','url':absolute(route),'price':f'{p["price"]:.2f}','priceCurrency':'USD','availability':'https://schema.org/InStock','itemCondition':'https://schema.org/NewCondition','seller':{'@id':absolute()+'#organization'},'shippingDetails':[{'@type':'OfferShippingDetails','shippingOrigin':{'@type':'DefinedRegion','addressCountry':'IT'},'shippingDestination':{'@type':'DefinedRegion','addressCountry':country},'shippingRate':{'@type':'MonetaryAmount','value':fee,'currency':'USD'},'shippingSettingsLink':absolute('shipping/')} for country,fee in [('US',0),('GB',0),('ZA',60)]]}
        data.append({'@type':'Product','@id':absolute(route)+'#product','name':p['fullName'],'description':p['description'],'image':[absolute('assets/'+x) for x in p['images']],'sku':p['id'].upper(),'brand':{'@id':absolute()+'#brand'},'category':p['category'],'material':p['material'],'color':p['colour'],'countryOfOrigin':{'@type':'Country','name':'Italy'},'offers':offer})
        web['mainEntity']={'@id':absolute(route)+'#product'}
    return {'@context':'https://schema.org','@graph':data}
def write(route,title,desc,body,crumbs=None,products=None,product=None,show_newsletter=True,noindex=False):
    crumbs=crumbs or []
    fulltitle=title if route=='' else title+' | '+BRAND
    jsdata={'products':PRODUCTS,'basePath':BASE,'email':EMAIL,'route':route,'preview':PREVIEW}
    robots='noindex, nofollow' if PREVIEW or noindex else 'index, follow, max-image-preview:large'
    schema=json.dumps(graph(route,fulltitle,desc,crumbs,products,product),ensure_ascii=False).replace('<','\\u003c')
    config=json.dumps(jsdata,ensure_ascii=False).replace('<','\\u003c')
    favicon='data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 64 64%22%3E%3Crect width=%2264%22 height=%2264%22 fill=%22%23132538%22/%3E%3Ctext x=%2232%22 y=%2243%22 text-anchor=%22middle%22 font-family=%22monospace%22 font-size=%2237%22 fill=%22%23f5f2eb%22%3ELI%3C/text%3E%3C/svg%3E'
    doc=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><base href="{("../" * len([x for x in route.split("/") if x])) or "./"}"><title>{esc(fulltitle)}</title><meta name="description" content="{esc(desc)}"><meta name="robots" content="{robots}"><meta name="theme-color" content="#132538"><meta name="color-scheme" content="light"><meta name="author" content="LA INFINITÉ (Pty) Ltd"><meta name="copyright" content="© 2026 LA INFINITÉ (Pty) Ltd"><link rel="canonical" href="{absolute(route)}"><meta property="og:type" content="{'product' if product else 'website'}"><meta property="og:site_name" content="{esc(BRAND)}"><meta property="og:title" content="{esc(fulltitle)}"><meta property="og:description" content="{esc(desc)}"><meta property="og:url" content="{absolute(route)}"><meta property="og:locale" content="en_US"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="{esc(fulltitle)}"><meta name="twitter:description" content="{esc(desc)}"><link rel="icon" type="image/svg+xml" href="{favicon}"><link rel="stylesheet" href="{url('styles/maison.css')}"><script type="application/ld+json">{schema}</script><script id="site-data" type="application/json">{config}</script><script src="{url('js/firebase-config.js')}"></script><script defer src="{url('js/store.js')}"></script><script type="module" src="{url('js/contact-firebase.mjs')}"></script></head><body>{header(route)}<main id="main">{body}</main>{newsletter() if show_newsletter else ''}{footer()}{dialogs()}<noscript><div class="noscript">You can browse all collections without JavaScript. For size selection and shopping bag assistance, <a href="mailto:{EMAIL}">email Client Services</a>. {link('sitemap/','View every page')}.</div></noscript></body></html>'''
    path=ROOT/(route+'index.html' if route else 'index.html');path.parent.mkdir(parents=True,exist_ok=True);path.write_text(doc)
    ROUTES.append(route)
def card(p):
    return f'''<article class="product-card" data-product-card data-id="{p['id']}" data-category="{p['category']}" data-price="{p['price']}" data-availability="{'request' if p['requestOnly'] else 'made-to-order'}"><a class="photo" href="{url('products/'+p['id']+'/')}" aria-label="Discover {esc(p['name'])}">{image(p['images'][0],p['fullName']+' — '+p['imageLabels'][0],width='1000',height='1000')}</a><div class="card-info"><div><h3>{link('products/'+p['id']+'/',esc(p['name']))}</h3><div class="meta">{esc(p['colour'])} · Made in Italy</div></div><span class="card-price">{money(p['price'])}</span></div></article>'''
def home():
    p=PRODUCTS[0]
    body=f'''<section class="hero"><div class="hero-copy"><p class="eyebrow">LA INFINITÉ / 01</p><h1>Zebra Stiletto</h1><p class="description">Zebra leather. Bordeaux lining. Made in Italy.</p><div class="actions">{link('products/zebra-stiletto/','Explore the piece ↗','text-link')}</div></div><a class="hero-art" href="{url('products/zebra-stiletto/')}" aria-label="Explore the Zebra Stiletto">{image(p['images'][0],'Zebra Stiletto, three-quarter view','eager',fetchpriority='high',width='1000',height='1000')}</a></section>
    <section aria-labelledby="creations-title"><div class="collection-intro"><div><p class="eyebrow">LA INFINITÉ</p><h2 id="creations-title">Selected pieces</h2></div>{link('new-in/','View collection','text-link')}</div><div class="wrap"><div class="product-grid">{''.join(card(x) for x in PRODUCTS)}</div></div></section>'''
    write('',BRAND+' | Handcrafted in Italy','The Zebra Stiletto and Sac L’Ivoire, created in Italy for LA INFINITÉ.',body)

def controls():
    return '''<div class="collection-controls"><details class="catalog-filter-menu"><summary>Filter &amp; sort <span class="active-filter-count" data-filter-count aria-label="Active filters"></span></summary><div class="catalog-filter-panel"><div class="filter-group"><label>Category<select data-filter="category" aria-label="Filter by category"><option value="all">All creations</option><option value="Shoes">Shoes</option><option value="Handbags">Handbags</option></select></label><label>Availability<select data-filter="availability" aria-label="Filter by availability"><option value="all">All availability</option><option value="made-to-order">Made to order</option><option value="request">By request</option></select></label><label>Price<select data-filter="price" aria-label="Filter by price"><option value="all">All prices</option><option value="under400">Under $400</option><option value="over400">$400 and above</option></select></label></div><label class="sort-label">Sort by<select data-sort><option value="featured">Featured</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option><option value="name">Name: A–Z</option></select></label><button class="filter-reset" type="button" data-clear-filters>Clear filters</button></div></details></div>'''

def collection(slug,title):
    ps=[p for p in PRODUCTS if slug in p['collections']]
    intros={'new-in':'The latest expressions of the Maison. Discover the pieces that begin a new chapter.','handbags':'Introducing L’Ivoire, the first handbag of LA INFINITÉ. Conceived with distinction. Handcrafted in Italy.','women':'Distinctive shoes and leather goods, brought to life through Italian craftsmanship.','gifts':'A considered gesture. Discover creations made to be treasured.'}
    if ps:
        body=breadcrumbs([(slug+'/',title)])+heading(title,intros[slug],'LA INFINITÉ collections')+f'''<section class="wrap" data-catalog>{controls()}<p class="results-count" data-results-count aria-live="polite">{len(ps)} creations</p><div class="product-grid" data-product-grid>{''.join(card(p) for p in ps)}</div><div class="empty-state" data-empty-results hidden><h2>No creations match your selection.</h2><p>Try a different filter or explore every current creation.</p><button class="button secondary" data-clear-filters>Clear filters</button></div></section>'''
    else:
        body=breadcrumbs([(slug+'/',title)])+heading(title,'','LA INFINITÉ collections')+f'''<section class="chapter"><div class="chapter-mark" aria-hidden="true">LI</div><h2>Collection enquiries</h2><p>The {esc(title.lower())} collection is not yet presented online. For availability enquiries or to share a particular request, please contact the Maison.</p><div class="actions">{button('contact/?subject='+slug,'Enquire with the Maison')}{link('new-in/','Explore current creations','text-link')}</div></section>'''
    write(slug+'/',title,intros.get(slug,f'Explore {title.lower()} at LA INFINITÉ. Contact the Maison for collection enquiries and future releases.'),body,[(slug+'/',title)],products=ps)
def accordion(title,content): return f'<details><summary>{title}</summary><div class="detail-content">{content}</div></details>'
def size_select():
    return f'''<div class="size-row"><span class="selection-label">Select your preferred size</span>{link('size-guide/','Size guide','text-link')}</div><div class="size-tabs" role="group" aria-label="Size system"><button class="size-tab" data-size-system="EU" aria-pressed="true">EU</button><button class="size-tab" data-size-system="US" aria-pressed="false">US</button><button class="size-tab" data-size-system="UK" aria-pressed="false">UK</button></div><div class="sizes" data-sizes role="group" aria-label="Preferred shoe size"></div><p class="fine muted">Indicative women’s size conversions. Final fit and size availability are confirmed by Client Services.</p>'''
def product_page(p):
    shoe=p['id']=='zebra-stiletto'
    extra=('<p>A classic pump balanced on a razor-sharp stiletto heel, with embossed leather panels and a sleek pointed toe. Butter-soft Italian leather wraps the shoe and heel. The Maison’s logo is showcased at the side of the heel counter.</p><ul><li>Italian leather construction</li><li>Zebra design with Bordeaux interior</li><li>Pointed toe and slender stiletto heel</li><li>Handmade to order in Italy</li></ul>' if shoe else '<p>The first handbag of LA INFINITÉ, crafted in Le Marche, Italy by master Italian craftsmen. Contrasting ivory and espresso panels frame a structured silhouette, finished with the Maison’s signature.</p><ul><li>Crocodile leather</li><li>Ivory and espresso colourway</li><li>Top handles and shoulder strap</li><li>Individually handcrafted in Italy</li></ul><p>Contact Client Services to confirm dimensions, material documentation and destination eligibility before placing your order.</p>')
    shipping='<p>Complimentary express shipping to Europe, the United Kingdom and the USA. Shipping to South Africa is $60. Other destinations receive an individual quote before an order is confirmed.</p>'
    shipping+= '<p>Each pair is handmade and custom-crafted. Production turnaround is 7–14 business days. Transit and customs time are additional.</p>' if shoe else '<p>Availability and production timing are confirmed individually by Client Services when you enquire.</p>'
    shipping+=link('shipping/','Read shipping & delivery')
    returns=('<p><strong>100% satisfaction guarantee.</strong> Love your shoes or send them back for free. Please contact the Maison to arrange the return. We assess the order and condition and provide the return instructions; your mandatory consumer rights remain protected.</p>' if shoe else '<p>Return and refund requests are assessed by the Maison according to the order, condition and reason for return, subject to all applicable consumer rights. Please contact us before sending an item back.</p>')+link('returns/','Read our returns & refunds policy')
    gallery=f'''<div class="gallery"><button class="main-product-image" data-zoom aria-label="Enlarge {esc(p['name'])}">{image(p['images'][0],p['fullName']+' — '+p['imageLabels'][0],'eager',id='product-main-image',fetchpriority='high',width='1000',height='1000')}<span class="zoom-hint">View closer</span></button><div class="thumbnails" aria-label="Product views">{''.join(f'<button class="thumbnail" data-gallery="{url("assets/"+im)}" data-alt="{esc(p["name"]+" — "+label)}" aria-label="{esc(label)}" aria-pressed="{str(i==0).lower()}">{image(im,label)}</button>' for i,(im,label) in enumerate(zip(p['images'],p['imageLabels'])))}</div></div>'''
    body=breadcrumbs([('women/' if shoe else 'handbags/','Women' if shoe else 'Handbags'),('products/'+p['id']+'/',p['name'])])+f'''<section class="pdp" data-product="{p['id']}">{gallery}<div class="product-details"><p class="eyebrow">{p['availability']} · Handcrafted in Italy</p><h1>{p['name']}</h1><p class="product-price">{money(p['price'])}</p><p class="fine muted">{'Tax included.' if shoe else 'Final tax and delivery details confirmed with your order.'} All prices in USD.</p><p class="product-description">{p['description']}</p><span class="selection-label">Colour</span><div class="colour-choice"><span class="swatch" aria-hidden="true"></span>{p['colour']}</div>{size_select() if shoe else ''}<div class="product-buy"><button class="button full" data-add-product>{'Add to bag' if shoe else 'Add to request bag'}</button><p class="status-message" data-product-status role="status"></p>{link('contact/?product='+p['id'],'Enquire about this creation','text-link')}</div><p class="delivery-note">{icon('delivery')}<span>Complimentary express delivery to Europe,<br>the United Kingdom &amp; USA.</span></p>{accordion('Details & composition',extra)}{accordion('Delivery & production',shipping)}{accordion('Returns & satisfaction',returns)}{accordion('Care & preservation','<p>Store in a dry place away from direct sunlight and heat. Avoid water, perfume and abrasive surfaces. For material-specific treatment, consult Client Services before applying any cleaning product.</p>'+link('care/','Care for your creation'))}</div></section>'''
    if shoe:
        body+=f'''<section class="detail-editorial"><div class="editorial-image">{image('la-nfinit--shoes-with_box.jpg','Zebra Stiletto with collector’s edition packaging')}</div><div class="editorial-copy"><p class="eyebrow">Beyond the creation</p><h2>A collector’s<br>first impression.</h2><p>Completely custom, high-quality collector’s edition packaging. Precision printing, handmade Italian construction, and a solid magnetic closure bring the Maison’s attention to detail to the moment of opening.</p><p class="fine">Each pair is individually crafted by master Italian craftsmen, combining tradition, quality and modern style.</p></div></section>'''
    else:
        body+=f'''<section class="story"><div class="story-photo">{image('la-infinit--30-accessory-detail.jpg','Crocodile leather detail on Sac L’Ivoire')}</div><div class="story-copy"><p class="eyebrow">Le Marche, Italy</p><h2>The hand of<br>the craftsman.</h2><p>Each L’Ivoire carries the character of its materials and the attention of the craftsman who made it. An individual creation, shaped by tradition and a modern point of view.</p>{link('about/','The story of the Maison','text-link')}</div></section>'''
    write('products/'+p['id']+'/',p['fullName'],f'{p["name"]} by LA INFINITÉ. {p["description"]} {money(p["price"])} USD.',body,[('women/' if shoe else 'handbags/','Women' if shoe else 'Handbags'),('products/'+p['id']+'/',p['name'])],product=p)
def contact():
    body=heading('At your service.','A question about a creation, a personal request, or assistance with an order. We would be pleased to hear from you.','Contact the Maison')+f'''<section class="form-layout"><aside class="form-aside"><p class="eyebrow">Client services</p><h2>A personal conversation.</h2><p>Write to our team for guidance on sizing, availability, delivery or care.</p><a class="contact-email text-link" href="mailto:{EMAIL}">{EMAIL}</a><hr class="rule"><p class="fine">Please include your order reference where relevant. For your privacy, do not send passwords, card details or identity documents.</p>{link('shipping/','Delivery information','text-link')}<br>{link('returns/','Returns & refunds','text-link')}</aside><form data-contact><div class="form-grid"><div class="field"><label for="contact-name">Full name</label><input id="contact-name" name="name" autocomplete="name" required maxlength="120"></div><div class="field"><label for="contact-email">Email address</label><input id="contact-email" name="email" type="email" autocomplete="email" required maxlength="254"></div><div class="field span-2"><label for="contact-subject">How may we help?</label><select id="contact-subject" name="subject"><option>Product enquiry</option><option>Private order request</option><option>Size & fit advice</option><option>Shipping & delivery</option><option>Returns & refunds</option><option>Maison Circle</option><option>Account access</option><option>Privacy request</option><option>Other enquiry</option></select></div><div class="field span-2"><label for="contact-message">Your message</label><textarea id="contact-message" name="message" required maxlength="5000"></textarea></div></div><label class="consent"><input type="checkbox" required><span>I understand that my information will be used to respond to this enquiry, as described in the {link('privacy/','Privacy notice')}.</span></label><p class="form-note">This form prepares an email in your email app. Please send it there to deliver your message.</p><button class="button" type="submit">Prepare my email</button><p data-form-status class="status-message" role="status"></p><a data-email-fallback hidden class="text-link">Open email again</a></form></section>'''
    write('contact/','Contact the Maison','Contact LA INFINITÉ Client Services for product enquiries, private orders, sizing, delivery and returns. Email '+EMAIL+'.',body,[('contact/','Contact')],show_newsletter=False)
def region_select(id='shipping-country'):
    return f'''<label for="{id}">Delivery destination</label><select id="{id}" data-shipping-country><option value="">Choose a destination</option><option value="ZA">South Africa</option><option value="US">United States</option><option value="GB">United Kingdom</option><option value="EUROPE">Europe (other)</option><option value="CA">Canada</option><option value="AU">Australia</option><option value="NZ">New Zealand</option><option value="ASIA">Asia</option><option value="MIDDLE_EAST">Middle East</option><option value="AFRICA">Africa (other)</option><option value="AMERICAS">Central & South America</option><option value="OTHER">Other destination</option></select>'''
def cart():
    body=heading('Your shopping bag.','Your considered selection. Each creation begins a personal conversation.','The Maison')+f'''<div id="empty-cart" class="wrap" hidden><div class="empty-state"><h2>Awaiting something exceptional.</h2><p>Your shopping bag is currently empty.</p>{button('new-in/','Explore the creations')}</div></div><section class="cart-layout" id="filled-cart"><div><div id="cart-items"></div><p class="fine muted" style="margin-top:25px">Your bag is saved on this device. Adding an item does not reserve stock or confirm an order.</p>{link('new-in/','Continue exploring','text-link')}</div><aside class="cart-summary"><h2>Your selection</h2><div class="totals"><span>Subtotal</span><span data-subtotal>$0.00</span></div><div class="field">{region_select()}</div><div class="totals"><span>Delivery</span><span data-delivery>Select destination</span></div><div class="totals total"><span data-total-label>Estimated total</span><span data-total>$0.00</span></div><p class="fine" data-cart-shipping-note>All prices are USD. Applicable taxes, duties and final delivery terms are confirmed before purchase.</p><button class="button full" data-request-order>Request this order</button><button class="button secondary full" style="margin-top:12px" disabled>PayPal checkout · Opening soon</button><p class="fine">Our online payment service is not yet open. Your request is prepared as an email; an order is confirmed only after the Maison agrees the details with you.</p><p data-cart-status role="status" class="status-message"></p><a data-order-email class="text-link" hidden>Open order email</a></aside></section>'''
    write('cart/','Shopping bag','Review your LA INFINITÉ creations, preferred sizes and delivery destination. Request an order personally with Client Services.',body,show_newsletter=False,noindex=True)
def account():
    body=heading('Your place in the Maison.','A personal relationship with LA INFINITÉ, and the privileges that grow with it.','My account')+f'''<section class="account-layout"><div class="account-panel"><div class="account-tabs" role="tablist" aria-label="Account options"><button role="tab" id="signin-tab" data-account-tab="signin" aria-selected="true" aria-controls="signin-panel">Sign in</button><button role="tab" id="join-tab" data-account-tab="join" aria-selected="false" aria-controls="join-panel" tabindex="-1">Become a member</button></div><div id="signin-panel" role="tabpanel" aria-labelledby="signin-tab"><h2>Welcome back.</h2><p>Online client accounts are opening soon. For an existing order or personal assistance, Client Services can help you directly.</p>{button('contact/?subject=account','Contact client services')}<p class="fine muted" style="margin-top:25px">Secure sign-in, order history and membership balances will be available when client accounts open.</p></div><div id="join-panel" role="tabpanel" aria-labelledby="join-tab" hidden><h2>Begin your acquaintance.</h2><p>Let the Maison know you would like to join. We will share account-opening information with you personally.</p><form data-membership><div class="field"><label for="member-name">Full name</label><input id="member-name" name="name" autocomplete="name" required maxlength="120"></div><div class="field"><label for="member-email">Email address</label><input id="member-email" name="email" autocomplete="email" type="email" required maxlength="254"></div><label class="consent"><input type="checkbox" required><span>I consent to being contacted about Maison Circle membership and have read the {link('privacy/','Privacy notice')}.</span></label><button class="button full" type="submit" style="margin-top:20px">Request an invitation by email</button><p class="fine" style="margin-top:15px">Opens your email app. No account is created by this form.</p><p data-form-status role="status" class="status-message"></p><a data-email-fallback hidden class="text-link">Open email again</a></form></div></div><div><div class="private-card"><div class="card-mark">LA INFINITÉ™</div><div><p class="eyebrow">Your relationship, recognised</p><h2>Maison Circle</h2><p class="fine">Four levels of acquaintance.<br>A world of considered privileges.</p></div></div><p class="fine muted" style="margin-top:25px">Discover Bronze, Silver, Gold and Platinum membership. Your level will reflect verified qualifying purchases.</p>{link('rewards/','Explore the Circle','text-link')}</div></section>'''
    write('account/','My account & membership','Your LA INFINITÉ client account and Maison Circle membership. Request an invitation and discover your privileges.',body,show_newsletter=False,noindex=True)
def rewards():
    tiers=[('Bronze',500,['Welcome to Maison Circle','Collection announcements','Personal client assistance']),('Silver',1000,['All Bronze privileges','Invitations to collection previews','Advance notice of new creations']),('Gold',5000,['All Silver privileges','Exclusive collection previews','Access to selected pre-sale invitations']),('Platinum',15000,['All Gold privileges','Exclusive previews before public release','Pre-sale access before market launch','A complimentary gift from the Maison'])]
    body=heading('Maison Circle.','The longer our acquaintance, the more there is to discover.','The client programme')+'<div class="rewards-intro"><p>A relationship recognised through four tiers. Your verified qualifying purchase total opens a new level of privileges with the Maison.</p></div><div class="wrap"><section class="tiers">'
    for i,(name,amount,perks) in enumerate(tiers):
        body+=f'<article class="tier"><p class="eyebrow">0{i+1} / The Circle</p><h2>{name}</h2><p class="threshold">{money(amount)}</p><small>Qualifying cumulative spend · USD</small><ul>'+''.join(f'<li>{x}</li>' for x in perks)+'</ul></article>'
    body+=f'''</section></div><section class="rewards-terms"><h2>A considered introduction.</h2><p>Maison Circle enrolment is being prepared alongside secure client accounts. You may request an invitation now. Benefits become available once the Maison confirms your membership and qualifying purchase record.</p>{button('account/?tab=join','Request an invitation')}<hr class="rule"><h2>How membership will work</h2><p>Membership levels are based on cumulative eligible merchandise purchases in US dollars, after discounts and excluding delivery charges, duties and separately itemised taxes. Refunded, cancelled, fraudulent or unpaid orders do not qualify. Returns may reduce the qualifying balance and resulting tier.</p><p>Bronze begins at $500; Silver at $1,000; Gold at $5,000; Platinum at $15,000. Every eligible completed order counts towards the next tier. A basket or order enquiry does not earn a balance.</p><p>Previews and pre-sales are invitations, subject to the availability of the relevant collection and any stated event conditions. They do not guarantee allocation. Platinum includes a complimentary gift chosen by the Maison, subject to availability and individual confirmation; it is not a cash entitlement.</p><p>Accounts and privileges are personal and non-transferable. We may correct errors, investigate misuse, or reasonably update future programme terms with notice. Changes do not override accrued contractual or mandatory consumer rights. Contact Client Services if you believe a balance or tier is incorrect.</p><p class="fine">Full activation and fulfilment details will be confirmed before enrolment. {link('contact/?subject=rewards','Speak with the Maison')}.</p></section>'''
    write('rewards/','Maison Circle — Client privileges','Discover Maison Circle: Bronze at $500, Silver at $1,000, Gold at $5,000 and Platinum at $15,000, with exclusive collection privileges.',body,[('rewards/','Maison Circle')])
def services():
    cards=[('Personal orders','For a creation offered by request, a particular preference, or a question about availability, begin a conversation with Client Services.','contact/?subject=private-order','Request a personal consultation'),('Size & fit','Explore our indicative EU, UK and US size guide. Our team will confirm fit and size availability before an order is finalised.','size-guide/','Discover the size guide'),('Care & preservation','Good care begins with knowing your materials. Discover the first principles of preserving your LA INFINITÉ creation.','care/','Care for your creation'),('Maison Circle','A considered programme for our clients, with privileges that develop as your relationship with the Maison grows.','rewards/','Explore your privileges')]
    body=heading('LA INFINITÉ Services.','Considered assistance, from your first enquiry to the care of a treasured creation.','At your service')+'<section class="services-grid wrap">'+''.join(f'<article class="service-card"><span class="number">0{i+1}</span><h2>{t}</h2><p>{d}</p>{link(p,l,"text-link")}</article>' for i,(t,d,p,l) in enumerate(cards))+'</section>'
    write('services/','LA INFINITÉ Services','Personal orders, size guidance, care and Maison Circle. Discover the services of LA INFINITÉ.',body,[('services/','Services')])
def about():
    body=heading('The Maison.','Founded in 2019. Shaped by a love of craft.','LA INFINITÉ')+f'''<section class="about-hero"><p>LA INFINITÉ began with shoes: a distinctive point of view, brought to life through Italian materials and the skill of the craftsman. From that beginning, the Maison is developing a wider world of leather goods, apparel and objects.</p><p>Our creations are handcrafted in Le Marche, Italy. Each carries the character of its materials, the attention of the hands that made it, and an expression of modern style.</p></section><div class="about-banner">{image('la-infinit--30-accessory-quarter.jpg','Sac L’Ivoire, the first handbag of the Maison')}</div><section class="about-hero" style="padding-top:60px"><p class="eyebrow">The first signatures</p><h2>From a silhouette<br>to a signature.</h2><p>The Zebra Stiletto pairs a pointed silhouette with expressive leather and a slender heel. Sac L’Ivoire, the Maison’s first handbag, introduces an interplay of ivory and espresso, structure and texture.</p><p>As the Maison grows, the intention remains personal: creations selected with care, made with attention, and offered through a direct relationship with our clients.</p>{button('new-in/','Explore the creations')}</section>'''
    write('about/','The Maison — Founded in 2019','Meet LA INFINITÉ, founded in 2019. Discover the Italian craftsmanship behind the Zebra Stiletto and Sac L’Ivoire, handcrafted in Le Marche.',body,[('about/','The Maison')])
def search_page():
    body=heading('Search the Maison.','','A creation, a collection, a detail')+f'''<form class="search-page-form" action="{url('search/')}" method="get"><label for="page-search" class="fine">Search</label><div class="search-box"><input id="page-search" type="search" name="q" maxlength="100" placeholder="Try ‘zebra’, ‘bag’ or ‘Italian leather’"><button aria-label="Search">{icon('search')}</button></div></form><section class="wrap" data-catalog data-search-page>{controls()}<p class="results-count" data-results-count aria-live="polite">2 creations</p><div class="product-grid" data-product-grid>{''.join(card(p) for p in PRODUCTS)}</div><div class="empty-state" data-empty-results hidden><h2>No creations found.</h2><p>Try a different search or explore the collections below.</p><button class="button secondary" data-clear-filters>Reset search & filters</button></div><div id="search-page-links" style="padding-bottom:40px"></div></section>'''
    write('search/','Search','Search LA INFINITÉ creations, collections and client services.',body,show_newsletter=False,noindex=True)
def legal_page(slug,title,description,content):
    nav=''.join(link(p+'/',n,aria_current='page' if p==slug else 'false') for p,n in LEGAL)
    body=heading(title,description,'Information · 8 October 2026')+f'<section class="legal-layout"><nav class="legal-nav" aria-label="Policies">{nav}</nav><article class="legal-copy">{content}</article></section>'
    write(slug+'/',title,description,body,[(slug+'/',title)],show_newsletter=False)

def information_pages():
    legal_page('shipping','Shipping & delivery','From our makers in Italy to your chosen destination.',f'''
    <h2>Delivery from Italy</h2><p>We welcome international enquiries and arrange shipping from Italy. Service availability depends on the delivery address, carrier coverage, customs rules and the materials in your order. Client Services confirms these details before accepting an order.</p>
    <h2>Shipping fees</h2><div class="table-wrap"><table><thead><tr><th>Destination</th><th>Shipping fee · USD</th><th>Service</th></tr></thead><tbody><tr><td>Europe, including the United Kingdom</td><td>Complimentary</td><td>Express shipping</td></tr><tr><td>United States</td><td>Complimentary</td><td>Express shipping</td></tr><tr><td>South Africa</td><td>$60.00</td><td>Shipping from Italy</td></tr><tr><td>Canada, Latin America & the Caribbean</td><td>Individual quote</td><td>Confirmed for your destination</td></tr><tr><td>Asia, Middle East & Oceania</td><td>Individual quote</td><td>Confirmed for your destination</td></tr><tr><td>Africa outside South Africa & other destinations</td><td>Individual quote</td><td>Confirmed for your destination</td></tr></tbody></table></div>
    <p>For destinations requiring a quote, the shipping charge remains unconfirmed until Client Services has your full destination and the parcel details. An unconfirmed charge is never treated as free shipping. Remote areas and destinations with service restrictions are checked individually; any additional amount requires your agreement before the order is accepted.</p>
    <div class="shipping-estimator"><h2>Check your destination</h2><div class="field">{region_select('delivery-estimate-country')}</div><p class="shipping-result" data-shipping-result aria-live="polite">Choose a destination to see the current shipping arrangement.</p></div>
    <h2>Production and transit</h2><p>The Zebra Stiletto is handmade and custom-crafted, with a production turnaround of 7–14 business days. This is the making period, not a guaranteed delivery date. Transit, public holidays, address verification and customs clearance are additional. L’Ivoire availability and production timing are confirmed individually with your order.</p>
    <h2>Taxes, duties and customs</h2><p>The displayed Zebra Stiletto price includes the taxes included in the stated product offer. Destination import duties, customs charges or locally assessed taxes may be additional unless your written order confirmation expressly includes them. Complimentary shipping does not by itself mean that import charges are prepaid. We will clarify the arrangement before payment.</p>
    <h2>Material and destination restrictions</h2><p>Some leather goods may require material documentation or permits for international shipment. In particular, crocodile leather may be subject to wildlife-trade and import restrictions. Client Services must verify the relevant material documentation and destination requirements before accepting an L’Ivoire order. Worldwide service is subject to that verification.</p>
    <h2>Delivery details and assistance</h2><p>Please provide a complete and accurate delivery address and reachable contact details. Once an order has been dispatched, available carrier tracking information will be shared with you. Contact us promptly about a delivery problem, visible damage, missing parcel or address correction. We will work with the carrier and explain the next steps; these procedures do not limit your legal rights.</p><p>{link('contact/?subject=shipping','Contact Client Services for a shipping quote')}.</p>''')
    legal_page('returns','Returns & refunds','Every request receives individual attention. Your consumer rights remain protected.',f'''
    <h2>Our approach</h2><p>If your creation is not right, please contact {EMAIL} with your order reference, the item concerned and a description of the issue. We assess requests fairly in light of the product, order terms, condition and reason for return. Assessment helps establish the appropriate remedy; it does not remove a refund, repair, replacement or cancellation right provided by applicable law.</p>
    <h2>The Zebra Stiletto satisfaction guarantee</h2><p>The Zebra Stiletto is offered with a 100% satisfaction guarantee: love your shoes or send them back for free. Contact Client Services to arrange your return and receive the appropriate instructions and prepaid return method. We will review the item and your request in line with that guarantee and any applicable statutory rights. Please do not arrange paid return shipping without contacting us first where a prepaid method is available.</p>
    <h2>L’Ivoire and other creations</h2><p>For Sac L’Ivoire, requests are assessed individually, including whether the item is faulty, incorrect, not as described, or eligible for a change-of-mind return under the order terms or applicable law. Any discretionary return arrangement and its shipping terms must be confirmed before purchase. We do not apply an undisclosed blanket “no refunds” rule.</p>
    <h2>Making a request</h2><ol><li>Email the Maison with your order reference and request. Photographs can help us assess damage or a fault, but do not send payment-card details.</li><li>We will confirm the relevant return instructions, address and any documentation required for international transit.</li><li>Pack the creation carefully. Where reasonably possible, include the original packaging, accessories and labels.</li><li>Once received, the Maison will inspect the return and explain the outcome, remedy and any lawful deduction, with reasons.</li></ol><p>For a change-of-mind return, please keep the item in saleable condition and try footwear only on a clean, soft indoor surface. A lack of original packaging does not automatically remove statutory rights for faulty or misdescribed goods.</p>
    <h2>Cancellations and individually made goods</h2><p>Tell us promptly if you wish to cancel. A genuinely personalised item or one made to your individual specifications may be treated differently under applicable cancellation law. Manufacturing an item after ordering does not, by itself, establish that every legal cancellation exception applies. Any relevant restriction must be explained before you place the order. Rights concerning faulty, unsafe or misdescribed goods remain unaffected.</p>
    <h2>Refunds</h2><p>Where a refund is approved or legally due, it will be returned through the original payment method where practicable, unless another lawful arrangement is agreed with you. We will confirm the amount and processing arrangements. Any mandatory refund deadline takes priority. Financial-institution processing times may apply after a refund is issued.</p><p>Delivery and return costs will be handled according to the applicable guarantee, agreed terms and law. We will not make an undisclosed restocking deduction. Any permitted deduction for diminished value must be justified and communicated.</p>
    <h2>Legal protections</h2><p>Mandatory rights in the jurisdiction applicable to your purchase prevail over this policy. Where applicable, South African consumer protections and European or UK distance-selling and product-conformity rights remain available. Contact us if you need help exercising them; an internal authorisation process must not obstruct a valid legal claim.</p><p>{link('contact/?subject=returns','Request return assistance')}.</p>''')
    legal_page('terms','Terms & conditions','The terms governing your use of the Maison’s website and personal order enquiries.',f'''
    <h2>1. The Maison and these terms</h2><p>This website presents LA INFINITÉ, a brand of LA INFINITÉ (Pty) Ltd (“the Maison”, “we”, “us”). Our contact address for website and order enquiries is {EMAIL}. These terms apply to use of the website. Any accepted purchase is also governed by the written order confirmation, applicable product information and mandatory consumer law.</p><p>The current website allows you to explore creations, save a shopping bag on your device and prepare an email enquiry. Online payment and secure client account facilities are not yet active. Registered business and fulfilment details, including the applicable return address, will be supplied in the transaction documentation before an order is concluded.</p>
    <h2>2. Intellectual property and ownership</h2><p>The LA INFINITÉ name, Maison identity, logos, original designs, product photography, written content, graphics, page layouts, code and other original website material are owned by or licensed to LA INFINITÉ (Pty) Ltd, except where a third-party owner is expressly identified. All applicable copyright, trademark, design and related rights are reserved.</p><p>You may view the website and retain reasonable copies for personal, non-commercial use. No permission is granted to reproduce, commercially exploit, distribute, modify, sell, impersonate, extract at scale or republish protected material without the rights holder’s written consent, except where applicable law permits it. The ™ symbol identifies a claimed trademark and does not represent that every mark is registered in every jurisdiction. Third-party names and software remain the property of their respective owners.</p>
    <h2>3. Acceptable use</h2><p>Use the website lawfully and respectfully. Do not attempt unauthorised access, interfere with operation, introduce harmful code, misuse forms, submit fraudulent orders, infringe rights or misrepresent your identity. Automated access must respect applicable law and must not impair the service. We may take proportionate steps to prevent misuse.</p>
    <h2>4. Product information and availability</h2><p>We aim to describe each creation accurately. Screen settings can affect how colours and textures appear, and natural materials and handcrafting can produce individual variation. Variations do not excuse goods that fail to match an agreed description. Please ask for material, dimension and fit information if it is important to your purchase.</p><p>Displayed availability is an invitation to enquire, subject to confirmation. Adding an item to the bag does not reserve it. Items offered by request require individual confirmation. No unsupported stock quantity, public review score or award is implied by a product listing.</p>
    <h2>5. Prices and ordering</h2><p>Displayed prices are in US dollars. The Zebra Stiletto is listed at $339.00 with tax included in the stated offer; Sac L’Ivoire is listed at $500.00. Shipping, applicable import charges and any other amounts will be clarified before your order is accepted. We do not charge an unconfirmed destination rate as if it were final.</p><p>A shopping bag, membership request, email enquiry or prepared email is not a binding order, payment, stock reservation or acceptance by the Maison. A purchase is concluded only after the Maison confirms the products, size or specification, final price, delivery terms and payment arrangements with you. You will have an opportunity to correct relevant details before accepting.</p><p>If a material pricing or availability error is discovered before acceptance, we will notify you and ask whether you wish to proceed on the corrected basis. We will not silently replace agreed terms. Any payment taken for an order that cannot lawfully be fulfilled will be handled according to your rights.</p>
    <h2>6. Delivery, cancellations and remedies</h2><p>The {link('shipping/','Shipping & delivery policy')} explains the current delivery arrangements. Production estimates and shipping estimates are distinct. The {link('returns/','Returns & refunds policy')} explains assistance and assessment. Product guarantees, accepted order terms and mandatory consumer protections take priority over inconsistent general wording.</p>
    <h2>7. Accounts and Maison Circle</h2><p>Client accounts are not yet open. No password or identity document is required to send an invitation request. Once activated, account holders must keep access credentials confidential and report suspected misuse. Membership thresholds and proposed benefits are described on the {link('rewards/','Maison Circle page')}; balances must be based on verified qualifying transactions, never on a shopping bag or unverified claim.</p>
    <h2>8. Communications and privacy</h2><p>Our {link('privacy/','Privacy notice')} describes the information handled through the current experience. Marketing consent is separate from order assistance. Sending a product enquiry does not automatically enrol you in marketing. Email links open your chosen email service, which is governed by its own terms.</p>
    <h2>9. Service availability and responsibility</h2><p>We take reasonable care to maintain the website but cannot promise uninterrupted access or compatibility with every device. We may make necessary updates, security repairs or service changes. To the extent lawfully permitted, we are not responsible for losses caused solely by events outside our reasonable control or your misuse of the website. Nothing excludes liability that cannot lawfully be excluded, including applicable liability for fraud, gross negligence, personal injury, defective products or mandatory consumer remedies.</p>
    <h2>10. Applicable law and disputes</h2><p>Subject to mandatory rules and consumer protections that apply to you, these terms are governed by South African law. This does not deprive a consumer of non-excludable protections or competent forums in their country where those rules apply. Please contact the Maison first so that we can try to resolve a concern. You remain free to approach a relevant regulator, ombud, consumer body or court.</p>
    <h2>11. Changes and contact</h2><p>We may update these website terms prospectively. The date above identifies this edition. Updated website terms do not retrospectively rewrite an already accepted order. If part of these terms is unenforceable, the remaining lawful provisions continue to apply. For permission requests, order queries or concerns, email {EMAIL}.</p>''')
    legal_page('privacy','Privacy notice','A clear account of how information is handled in this edition of the website.',f'''
    <h2>1. Who is responsible</h2><p>LA INFINITÉ (Pty) Ltd operates the LA INFINITÉ brand and determines how information received by the Maison is used. For privacy questions, access requests or withdrawal of consent, contact {EMAIL} with “Privacy request” in the subject line. Do not include sensitive identity or financial documents in an initial message.</p>
    <h2>2. Information you choose to provide</h2><p>Until our secure Firebase service is configured, contact and newsletter forms prepare email requests for your review; nothing is delivered until you send the email. Once Firebase is activated, the contact form sends your name, email, subject and message directly to our restricted Client Services dashboard, and newsletter requests are stored with consent in a pending-verification register. If you send it, we receive the information included in your message, such as your name, email address, enquiry, product selections, preferred size and chosen destination.</p><p>General customer checkout and card payments are not yet active. When invited Maison Circle registration is activated, Firebase Authentication manages account credentials and verified email addresses; administrators cannot view passwords. We do not collect or store payment-card numbers. These features only operate after the relevant backend configuration and deployment.</p>
    <h2>3. Device storage and technical information</h2><p>Your shopping bag, selected delivery destination and privacy choices are stored on your device to support the features you use. If you opt into analytics, a random visit identifier and limited page-path records are stored locally. They are not currently transmitted to an external analytics service. Do not store private information in website URLs.</p><p>The hosting service may process ordinary connection information, such as IP address, browser details and access logs, to deliver and secure the website. An owner-only preview may also require the hosting platform’s own sign-in. That platform’s separate account and hosting privacy terms apply to its processing. See our {link('cookies/','Cookie policy')} for the website’s named storage items.</p>
    <h2>4. Why we use information</h2><ul><li>To respond to an enquiry or membership invitation request that you send.</li><li>To discuss and, where agreed, fulfil an order and provide aftercare.</li><li>To meet legal, accounting and dispute-resolution obligations where applicable.</li><li>To send Maison news only where we have a valid marketing permission or other lawful basis that applies.</li><li>To protect the website and prevent misuse in a proportionate way.</li></ul><p>Depending on the activity and applicable law, the basis may be steps at your request before a contract, performance of an accepted contract, legal obligations, appropriate legitimate interests or your freely given consent. Optional storage and voluntary marketing requests use separate choices.</p>
    <h2>5. Marketing choices</h2><p>Our newsletter form asks for a separate, unticked permission. Before Firebase activation it prepares an email request; after activation it records a pending-verification consent request in the secure system. Neither action itself confirms a verified subscription. The Maison will process the request before sending marketing. You may withdraw marketing consent at any time by emailing us. Withdrawing does not affect necessary order messages or the lawfulness of earlier processing.</p>
    <h2>6. Sharing and international processing</h2><p>We do not sell information received through this website. Information you submit may be handled by email and website hosting providers, and by Google Firebase/Cloud hosting and authentication services once enabled. Where an order is actually accepted, makers, payment processors, delivery partners or professional advisers may handle the minimum necessary information. Access should be limited to what is necessary for the purpose.</p><p>Email, hosting and international fulfilment may involve processing in more than one country. Where applicable law requires safeguards for an international transfer, those safeguards must be in place before the relevant transfer. Additional provider and transaction details will be supplied when the relevant service becomes active. We do not claim that every future integration is already operating.</p>
    <h2>7. Retention and security</h2><p>We retain correspondence, enquiry records, verified membership records and subscription requests only as long as reasonably necessary for the purpose, legal recordkeeping or a justified dispute, after which they should be deleted or appropriately de-identified. Exact periods depend on the record and applicable obligation. Local storage periods are set out in the Cookie policy, and you can remove device data through your browser.</p><p>Reasonable technical and organisational safeguards are required for information entrusted to the Maison. No internet transmission is entirely risk-free. Please use the dedicated enquiry address and avoid sending passwords or full payment details by email.</p>
    <h2>8. Your rights</h2><p>Depending on applicable law, you may request access, correction, deletion, restriction, objection, portability, or withdrawal of consent. We may need proportionate verification before disclosing personal information. We will explain any lawful limitation and respond within applicable time limits. You may also complain to a competent data protection authority, including South Africa’s Information Regulator where relevant.</p><p>We do not use this edition of the website to make automated decisions with legal or similarly significant effects. Future loyalty tiers will be based on verified transaction records and should be reviewable by Client Services.</p>
    <h2>9. Children and updates</h2><p>A Children collection does not mean the website invites children to provide personal information. Purchases and personal-information requests should be handled by an adult with legal capacity. If a child’s information has been provided unintentionally, contact us so that we can address it appropriately.</p><p>This notice will be updated when features or practices change. Please review the date above. {link('contact/?subject=privacy','Contact the Maison about privacy')}.</p>''')
    legal_page('cookies','Cookie policy','You decide whether optional storage is used on your device.',f'''
    <h2>Cookies and similar storage</h2><p>Cookies are small records a website can save in your browser. Local storage is another browser feature used to retain information between visits. This policy covers both. Essential storage supports features you request, such as your shopping bag and privacy preferences. Optional analytics remain off until you choose to enable them.</p>
    <h2>What this website stores</h2><div class="table-wrap"><table><thead><tr><th>Name</th><th>Purpose</th><th>Duration</th></tr></thead><tbody><tr><td>li_consent</td><td>Essential cookie recording your privacy choice and policy version.</td><td>180 days</td></tr><tr><td>li_cart_v1</td><td>Local storage for product IDs, sizes and quantities in your bag.</td><td>30 days after the last bag update</td></tr><tr><td>li_country_v1</td><td>Local storage for your selected delivery destination.</td><td>30 days after selection</td></tr><tr><td>li_visit</td><td>Optional analytics cookie containing a random identifier.</td><td>30 days</td></tr><tr><td>li_analytics_v1</td><td>Optional local page-path and timestamp records, capped at 100 entries.</td><td>30 days; earlier on withdrawal</td></tr></tbody></table></div>
    <p>These entries do not contain passwords, payment-card details or the information typed into contact, newsletter or membership forms. Local shopping bag data is not a secure account or order record. In this edition, optional browsing records stay on your device: no external analytics, advertising or cross-site tracking provider receives them.</p>
    <h2>Manage or withdraw consent</h2><p>Choose “Essential only” to decline optional storage, “Accept optional” to enable it, or “Manage preferences” for a specific choice. Both acceptance and refusal leave essential shopping features available. Closing preferences without saving does not grant consent.</p><p><button class="button secondary" data-cookie-settings>Open cookie preferences</button></p><p>You can change your choice at any time using the footer. Turning analytics off removes the optional identifier and local browsing records. Expired records are discarded when the website is next used. Your browser can also block or clear cookies and storage; doing so may empty your shopping bag or make the website ask for your privacy choice again.</p>
    <h2>Third parties and future features</h2><p>The hosting platform and the email service you use may operate their own necessary storage under their privacy terms. Future account, newsletter, analytics or payment integrations may use additional storage. Those features must be documented and, where required, gated behind your consent before activation. There are no advertising cookies in this edition.</p><p>For related information, read the {link('privacy/','Privacy notice')} or contact {EMAIL}.</p>''')
    legal_page('accessibility','Accessibility','The Maison should be welcoming and usable.',f'''
    <h2>Our approach</h2><p>We aim to make the website understandable and operable across devices, assistive technologies and different browsing needs. This edition includes keyboard-accessible navigation, labelled form controls, meaningful image descriptions, visible focus indicators, a skip-to-content link and support for reduced-motion preferences.</p><h2>Using the website</h2><p>The menu, search and cookie preferences can be opened with a keyboard. Press Escape to close a dialog. Product views and size choices are labelled; shopping bag updates and form messages are announced as status information where supported. Browser zoom and text enlargement are supported.</p><h2>Assistance and feedback</h2><p>If a page or interaction prevents you from using the site, please email {EMAIL}. Tell us which page was affected, what you were trying to do and, if helpful, your browser or assistive technology. Do not include sensitive information. Client Services can assist with product information, sizes and ordering by email.</p><h2>Continued improvement</h2><p>We will review reported barriers as the website develops. We do not claim that an independent accessibility certification has been completed. Your feedback helps us prioritise specific improvements.</p>''')
    legal_page('care','Care for your creation','Attention to materials preserves the pleasure of owning them.',f'''
    <h2>Italian leather</h2><p>Keep your creation away from prolonged sunlight, direct heat, moisture, oils and fragrance. Blot accidental moisture gently with a clean, soft cloth and allow the piece to dry naturally. Do not use a hair dryer or place it beside a heater.</p><h2>Your Zebra Stiletto</h2><p>Try new shoes on a clean, soft indoor surface while checking fit. Allow leather footwear to rest between wears. Keep the shape supported without stretching the upper, and store each shoe so that the surfaces do not rub against one another. Ask a qualified leather or footwear specialist about repairs.</p><h2>Your Sac L’Ivoire</h2><p>Avoid overfilling the bag or suspending it by its handles for long periods. Support its shape lightly for storage, protect hardware from hard surfaces and keep dark fabrics from transferring colour onto lighter panels. Crocodile leather requires material-specific care: consult the Maison before using creams, solvents or water-based cleaning products.</p><h2>Packaging and storage</h2><p>Store in a cool, dry and ventilated place, protected from dust. Allow damp items to dry fully before returning them to their packaging. The presentation box is part of the experience, but it should not trap moisture around a leather creation.</p><h2>Personal assistance</h2><p>For stains, damage, repair options or uncertainty about a treatment, contact the Maison with photographs and your order reference. These general suggestions do not replace specific instructions supplied with your item.</p><p>{link('contact/','Ask about care and preservation')}.</p>''')
def size_guide():
    rows=''.join(f'<tr><td>{eu}</td><td>{eu-30}</td><td>{eu-33}</td></tr>' for eu in range(35,43))
    body=heading('A considered fit.','Indicative women’s shoe size conversions.','Size guide')+f'''<section class="legal-layout"><nav class="legal-nav" aria-label="Size assistance">{link('products/zebra-stiletto/','The Zebra Stiletto')}{link('contact/?subject=sizing','Ask for fit advice')}{link('returns/','Returns & satisfaction')}</nav><article class="legal-copy"><h2>EU, US & UK sizing</h2><p>Use the table as an initial guide when expressing your preferred size. Conversions vary by maker, style and fit. This is not a manufacturer-verified size chart or a statement of available stock. Client Services will confirm the correct fit and the sizes available for your order.</p><table class="size-table"><thead><tr><th>EU</th><th>US · Women</th><th>UK · Women</th></tr></thead><tbody>{rows}</tbody></table><h2>Choosing your size</h2><p>If you usually wear a half size, have a wide or narrow fit, or are between two sizes, please contact the Maison before placing an order. Share the size you wear in a well-fitting pointed pump and any fit preferences. Do not assume that a standard conversion guarantees the same fit across brands.</p><h2>Your selection stays consistent</h2><p>Switching the size display between EU, US and UK does not change the underlying preferred size in your bag. Your request records both the chosen display and its indicative EU equivalent so that the Maison can confirm it with you.</p>{button('contact/?subject=sizing','Ask Client Services')}</article></section>'''
    write('size-guide/','Size guide — EU, US & UK','An indicative EU, US and UK women’s shoe size guide for LA INFINITÉ. Speak with Client Services to confirm fit and availability.',body,[('size-guide/','Size guide')],show_newsletter=False)
def sitemap_page():
    groups=[('Collections',[(s+'/',n) for s,n in NAV]),('The Maison',[('about/','Our story'),('products/zebra-stiletto/','Zebra Stiletto'),('products/sac-livoire/','Sac L’Ivoire'),('rewards/','Maison Circle'),('contact/','Contact'),('account/','My account'),('cart/','Shopping bag'),('search/','Search')]),('Information',[(s+'/',n) for s,n in LEGAL]+[('size-guide/','Size guide'),('care/','Care for your creation')])]
    body=heading('Sitemap.','Every chapter of the Maison.','Find your way')+'<section class="sitemap-grid">'+''.join('<div><h2>'+t+'</h2>'+''.join(link(p,esc(n)) for p,n in items)+'</div>' for t,items in groups)+'</section>'
    write('sitemap/','Sitemap','Explore every collection, product, client service and information page at LA INFINITÉ.',body,show_newsletter=False)

def main():
    home()
    for s,n in NAV:
        if s!='services': collection(s,n)
    for p in PRODUCTS: product_page(p)
    contact();cart();account();rewards();services();about();search_page();information_pages();size_guide();sitemap_page()
    body='<section class="not-found"><p class="eyebrow">404</p><h1>Page not found</h1><p>This page could not be found. Let us return you to the Maison.</p>'+button('','Return to the Maison')+'</section>'
    write('not-found/','Page not found','The requested page could not be found.',body,show_newsletter=False,noindex=True)
    (ROOT/'404.html').write_text((ROOT/'not-found/index.html').read_text().replace('<base href="../">','<base href="./">'))
    publicroutes=[r for r in ROUTES if r not in ['cart/','account/','search/','not-found/']]
    sitemap='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'  <url><loc>{esc(absolute(r))}</loc></url>\n' for r in publicroutes)+'</urlset>\n'
    (ROOT/'sitemap.xml').write_text(sitemap)
    (ROOT/'.nojekyll').touch()
    # Publish from repository root; do not copy generated pages to dist.
    print(json.dumps({'pages':len(ROUTES),'products':len(PRODUCTS),'origin':ORIGIN,'basePath':BASE,'preview':PREVIEW,'output':str(ROOT)}))
if __name__=='__main__': main()
